import numpy as np

BG_COLOUR = (144, 72, 17)
BALL_COLOUR = (236, 236, 236)
LEFT_GUY_COLOUR = (213, 130, 74)
RIGHT_GUY_COLOUR = (92, 186, 92)

GAME_BOTTOM = 194
GAME_TOP = 34
SCALED_PADDLE_HEIGHT = 16.0
FPS = 60
GAME_PLAYABLE_HEIGHT = GAME_BOTTOM - GAME_TOP
GAME_WIDTH = 160

RIGHT_ACTION_START = 4
RIGHT_ACTION_END = 6
LEFT_ACTION_END = 8
LEFT_PLAYER_START_BUTTON = -1
RIGHT_PLAYER_START_BUTTON = 0

BLANK_ACTION = np.zeros(shape=(16,), dtype=np.int)
BLANK_ACTION[LEFT_PLAYER_START_BUTTON] = 1
BLANK_ACTION[RIGHT_PLAYER_START_BUTTON] = 1

N_CLASSES = 2
ALL_ACTIONS = np.eye(N_CLASSES, dtype=np.int)

TIMEOUT_THRESH = 2_000

GENE_SIZE = 46
IND_PB = 0.9
SIGMA = 0.9
MU = 0

CX_PB = 0.5
MUT_PB = 0.9

# OFTEN CHANGED
N_GENS = 5
GAMES_TO_PLAY = 5
POPULATION_SIZE = 16

TOURN_SIZE = POPULATION_SIZE // 2
HALL_OF_FAME_AMOUNT = TOURN_SIZE

RENDER = False

NETWORK_SHAPE = [
    5, 4, 2
]
