import numpy as np

FPS = 60

N_CLASSES = 2
ALL_ACTIONS = np.eye(N_CLASSES, dtype=np.int)

TIMEOUT_THRESH = 8_000

NETWORK_SHAPE = [
    6, 2, 2
]

BIAS = True

PROBABILITY_OF_MUTATING_A_SINGLE_GENE = 0.9
GAUSSIAN_MUTATION_SIGMA = 0.9
GAUSSIAN_MUTATION_MEAN = 0
GAUSSIAN_MUTATION_PROBABILITY = 0.9

CROSSOVER_BLEND_PROBABILITY = 0.9
CROSSOVER_BLEND_ALPHA = 0.9

GENERATIONS_BEFORE_SAVE = 10
NUMBER_OF_HARD_CODED_RANDOM_AIS = 10
GAMES_TO_PLAY_AGAINST_SELF = 10
GAMES_TO_PLAY = NUMBER_OF_HARD_CODED_RANDOM_AIS + GAMES_TO_PLAY_AGAINST_SELF
POPULATION_SIZE = 640

TOURNAMENT_SIZE = POPULATION_SIZE // 4
HALL_OF_FAME_AMOUNT = 5

RENDER = False
WIN_SCORE = 5
TIME_SCALAR = 100.0

BACKGROUND_COLOUR = (150, 150, 150)
GAME_HEIGHT = 600
GAME_WIDTH = 600

RIGHT_GUY_COLOUR = (50, 255, 50)
LEFT_GUY_COLOUR = (50, 50, 255)
BALL_COLOUR = (255, 255, 255)
SCORE_COLOUR = (200, 0, 0)

STARTING_POSITION_Y = GAME_HEIGHT / 2

PADDLE_EDGE_DISTANCE = 0
PADDLE_HEIGHT = 40
PADDLE_WIDTH = 10
PADDLE_SPEED = 1

BALL_SIZE = (10, 10)
BALL_SPEED = 10
BALL_MIN_BOUNCE = 0.1

LEFT_GUY_X = PADDLE_EDGE_DISTANCE
RIGHT_GUY_X = GAME_WIDTH - PADDLE_EDGE_DISTANCE - PADDLE_WIDTH
