from enum import Enum

# Consts
from config import POPULATION_SIZE


class Direction(Enum):
    UP = 0
    DOWN = 1
    NOOP = 2


FPS = 60

TOTAL_TIMEOUT_THRESH = 20_000
LAST_HIT_TIMEOUT_THRESH = 1_000

# I want some depth to try and have higher abstract thoughts
NETWORK_SHAPE = [
    8, 4, len(Direction)
]
BIAS = True

GAUSSIAN_MUTATION_MEAN = 0

GENERATIONS_BEFORE_SAVE = 3

HALL_OF_FAME_AMOUNT = min(POPULATION_SIZE, 10)
TOURNAMENT_SIZE = min(POPULATION_SIZE, POPULATION_SIZE // 4)

RENDER = False

WIN_SCORE = 500
PADDLE_HIT_SCORE = 0.5
POINT_SCORE = 1.0
BONUS_SCALAR = 50.0
SCORE_DECAY = 0.99999

BALL_SPEED_UPPER = 0.2

BACKGROUND_COLOUR = (150, 150, 150)
RIGHT_GUY_COLOUR = (50, 255, 50)
LEFT_GUY_COLOUR = (50, 50, 255)
BALL_COLOUR = (255, 255, 255)
SCORE_COLOUR = (200, 0, 0)

GAME_HEIGHT = 600.0
GAME_WIDTH = 600.0

STARTING_POSITION_Y = GAME_HEIGHT / 2.0
PADDLE_EDGE_DISTANCE = 0.0
PADDLE_HEIGHT = 40.0
PADDLE_WIDTH = 10.0
PADDLE_SPEED = 10.0

BALL_SIZE = (10.0, 10.0)
BALL_SPEED = 4.0
BALL_MIN_BOUNCE = 0.1

LEFT_GUY_X = PADDLE_EDGE_DISTANCE + PADDLE_WIDTH
RIGHT_GUY_X = GAME_WIDTH - PADDLE_EDGE_DISTANCE - PADDLE_WIDTH

TIME_STEP = 1.0
